## 1. 类的定义
## 2. 装饰器
## 3. torch.enisum

In [8]:
# 实现一个加法 model
# nn.Module
class AddModel: 
    def __init__(self, n): 
        self.n = n 
        print(f"Add Model Initialized: {n}")

    # 前向传播，更像是一个函数
    def forward(self, x):
        res = x + self.n
        print(f"result = {res}")
        return res

In [9]:
model = AddModel(5)

Add Model Initialized: 5


In [10]:
output = model.forward(2)

result = 7


In [11]:
def gift(): 
    print("My Gift")

In [12]:
gift()

My Gift


In [13]:
def gift_wrapper(func): 
    def wrapper(): 
        print("Begining wrappering...")
        func()
        print("End.")
    return wrapper

In [14]:
@gift_wrapper
def gift(): 
    print("My Gift")

In [15]:
gift()

Begining wrappering...
My Gift
End.


In [1]:
import torch

In [7]:
A = torch.tensor([
    [1.0, 2.0, 3.0],
    [4.0, 5.0, 6.0]
])

In [14]:
B = torch.ones(6).reshape(2, 3)

In [15]:
res = A @ B # [B, L, H, D] 
res

RuntimeError: mat1 and mat2 shapes cannot be multiplied (2x3 and 2x3)

In [18]:
# 点对点乘 哈达玛积
res = torch.einsum('ij, ij->ij', A, B)
res

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [23]:
# 自查进行矩阵乘法
res = torch.einsum('ik, jk->ij', A, B)
res

tensor([[ 6.,  6.],
        [15., 15.]])

In [24]:
res = A @ B.T
res

tensor([[ 6.,  6.],
        [15., 15.]])